KendoUIAPIs/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using KendoUIAPIs.Areas.HelpPage.Models;

namespace KendoUIAPIs.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

KendoUIAPIs/Controllers/KendoAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KendoUIAPIs.Dtos;
using System.Net.Http;
using System.Web.Http;
using System.Net;
using System.Text;

namespace KendoUIAPIs.Controllers
{
    public class KendoAPIController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GridInlineEditing()
        {
            return View();
        }

        public ActionResult GridMVVM()
        {
            return View();
        }

        public ActionResult MasterDetailGrid()
        {
            return View();
        }

        public ActionResult SignalR()
        {
            return View();
        }

        public ActionResult Main()
        {

            return File("~/Views/KendoAPI/Main.html", "text/html");
        }

        public ActionResult DetailTemplate()
        {
            return File("~/Views/KendoAPI/Templates/detail.tmpl.html", "text/html");
        }

        public ActionResult IndexTemplate()
        {
            return File("~/Views/KendoAPI/Templates/index.tmpl.html", "text/html");
        }

        public ActionResult View3Template()
        {
            return File("~/Views/KendoAPI/Templates/view3.tmpl.html", "text/html");
        }

        public ActionResult SPATemplates()
        {
            StringBuilder htmlContent = new StringBuilder();

            htmlContent.Append(System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath("~/Views/KendoAPI/Templates/detail.tmpl.html")));
            htmlContent.Append(System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath("~/Views/KendoAPI/Templates/index.tmpl.html")));
            htmlContent.Append(System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath("~/Views/KendoAPI/Templates/view3.tmpl.html")));

            return Content(htmlContent.ToString());
        }

        public ActionResult KendoApp()
        {
            return View();
        }
    }
}

KendoUIAPIs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@

    @RenderSection("scriptsHeader", required: false)
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a>
                </p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        @*<li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                        <li>@Html.ActionLink("GridInlineEditing", "GridInlineEditing", "KendoAPI", null, null)  </li>
                        <li>@Html.ActionLink("GridMVVM", "GridMVVM", "KendoAPI", null, null)  </li>
                        <li>@Html.ActionLink("MasterDetailGrid", "MasterDetailGrid", "KendoAPI", null, null)  </li>
                        <li>@Html.ActionLink("SignalR", "SignalR", "KendoAPI", null, null)  </li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @*  @Scripts.Render("~/bundles/jquery")*@
    @RenderSection("scripts", required: false)
    
</body>
</html>